# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7810fc11c9a5f67e1e40560f87a922ad45449e3e07c9ad8ec675bfe8dcc5304d97a6ecb30163f921bcbc768591e59dea3103d62fdae6831dc6c4cda80a500d35

test:
  secret_key_base: bcdba06b2d0d890e7be951751c6633738e14b1c5217da7432bb173f50c57b6773adfc11f096a91564b783030bc8cc06a89467c6e0c4b892e64616810d8689f24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
